# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:                               # это описание события, по которому будет запускаться наш скрипт.
  push:
    branches:
      - 'master'
env:
  IMAGE_NAME: cicd:0.0.1-SNAPSHOT

jobs:
  build:
    runs-on: ubuntu-20.04        # тут мы можем выбрать целевую ОС
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1   # позволяет переиспользовать другие экшены, так например при помощи экшена actions/setup-java мы устанавливаем окружение для Java 11
        with:                         # При помощи with мы можем указать параметры с которыми запускаем действие, по сути это аргументы, которые будут передаваться в экшен.
          java-version: 11
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build a container image from our Spring Boot app using Paketo.io / Cloud Native Build Packs
        run: mvn spring-boot:build-image
      - name: Tag & publish to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID

